endpoints: dict[str, dict] = {}
endpoints["dspace_ccb"] = {}
endpoints["dspace_ccb"]["enabled"] = True
endpoints["dspace_ccb"]["name"] = (
    "FUNDACION UNIVERSITARIA EMPRESARIAL DE LA CAMARA DE COMERCIO DE BOGOTA- UNIEMPRESARIAL"
)
endpoints["dspace_ccb"]["ror"] = "https://ror.org/02yr3f298"
endpoints["dspace_ccb"]["url"] = "https://bibliotecadigital.ccb.org.co/server/oai/request"
endpoints["dspace_ccb"]["metadataPrefix"] = "dim"
endpoints["dspace_ccb"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ccb"]["checkpoint"] = {}
endpoints["dspace_ccb"]["checkpoint"]["enabled"] = True
endpoints["dspace_ccb"]["checkpoint"]["selective"] = False
endpoints["dspace_ccb"]["checkpoint"]["days"] = 30
endpoints["dspace_unaula"] = {}
endpoints["dspace_unaula"]["enabled"] = True
endpoints["dspace_unaula"]["name"] = "Universidad Autónoma Latinoamericana"
endpoints["dspace_unaula"]["ror"] = "https://ror.org/05tkb8v92"
endpoints["dspace_unaula"]["url"] = "http://repositorio.unaula.edu.co:8080/server/oai/request"
endpoints["dspace_unaula"]["metadataPrefix"] = "dim"
endpoints["dspace_unaula"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unaula"]["checkpoint"] = {}
endpoints["dspace_unaula"]["checkpoint"]["enabled"] = True
endpoints["dspace_unaula"]["checkpoint"]["selective"] = False
endpoints["dspace_unaula"]["checkpoint"]["days"] = 30
endpoints["dspace_unal"] = {}
endpoints["dspace_unal"]["enabled"] = True
endpoints["dspace_unal"]["name"] = "UNIVERSIDAD NACIONAL DE COLOMBIA"
endpoints["dspace_unal"]["ror"] = "https://ror.org/059yx9a68"
endpoints["dspace_unal"]["url"] = "https://repositorio.unal.edu.co/oai/request"
endpoints["dspace_unal"]["metadataPrefix"] = "dim"
endpoints["dspace_unal"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unal"]["checkpoint"] = {}
endpoints["dspace_unal"]["checkpoint"]["enabled"] = True
endpoints["dspace_unal"]["checkpoint"]["selective"] = False
endpoints["dspace_unal"]["checkpoint"]["days"] = 30
endpoints["dspace_pedagogica"] = {}
endpoints["dspace_pedagogica"]["enabled"] = True
endpoints["dspace_pedagogica"]["name"] = "UNIVERSIDAD PEDAGOGICA NACIONAL"
endpoints["dspace_pedagogica"]["ror"] = "https://ror.org/023m5rq87"
endpoints["dspace_pedagogica"]["url"] = "http://repositorio.pedagogica.edu.co/oai/request"
endpoints["dspace_pedagogica"]["metadataPrefix"] = "dim"
endpoints["dspace_pedagogica"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_pedagogica"]["checkpoint"] = {}
endpoints["dspace_pedagogica"]["checkpoint"]["enabled"] = True
endpoints["dspace_pedagogica"]["checkpoint"]["selective"] = False
endpoints["dspace_pedagogica"]["checkpoint"]["days"] = 30
endpoints["dspace_uptc"] = {}
endpoints["dspace_uptc"]["enabled"] = True
endpoints["dspace_uptc"]["name"] = "UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA - UPTC"
endpoints["dspace_uptc"]["ror"] = "https://ror.org/04vdmbk59"
endpoints["dspace_uptc"]["url"] = "https://repositorio.uptc.edu.co/server/oai/request"
endpoints["dspace_uptc"]["metadataPrefix"] = "dim"
endpoints["dspace_uptc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uptc"]["checkpoint"] = {}
endpoints["dspace_uptc"]["checkpoint"]["enabled"] = True
endpoints["dspace_uptc"]["checkpoint"]["selective"] = False
endpoints["dspace_uptc"]["checkpoint"]["days"] = 30
endpoints["dspace_unicauca"] = {}
endpoints["dspace_unicauca"]["enabled"] = True
endpoints["dspace_unicauca"]["name"] = "UNIVERSIDAD DEL CAUCA"
endpoints["dspace_unicauca"]["ror"] = "https://ror.org/04fybn584"
endpoints["dspace_unicauca"]["url"] = "http://repositorio.unicauca.edu.co:8080/oai/request"
endpoints["dspace_unicauca"]["metadataPrefix"] = "dim"
endpoints["dspace_unicauca"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unicauca"]["checkpoint"] = {}
endpoints["dspace_unicauca"]["checkpoint"]["enabled"] = True
endpoints["dspace_unicauca"]["checkpoint"]["selective"] = False
endpoints["dspace_unicauca"]["checkpoint"]["days"] = 30
endpoints["dspace_utp"] = {}
endpoints["dspace_utp"]["enabled"] = True
endpoints["dspace_utp"]["name"] = "UNIVERSIDAD TECNOLOGICA DE PEREIRA - UTP"
endpoints["dspace_utp"]["ror"] = "https://ror.org/01d981710"
endpoints["dspace_utp"]["url"] = "https://repositorio.utp.edu.co/server/oai/request"
endpoints["dspace_utp"]["metadataPrefix"] = "dim"
endpoints["dspace_utp"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_utp"]["checkpoint"] = {}
endpoints["dspace_utp"]["checkpoint"]["enabled"] = True
endpoints["dspace_utp"]["checkpoint"]["selective"] = False
endpoints["dspace_utp"]["checkpoint"]["days"] = 30
endpoints["dspace_ucaldas"] = {}
endpoints["dspace_ucaldas"]["enabled"] = True
endpoints["dspace_ucaldas"]["name"] = "UNIVERSIDAD DE CALDAS"
endpoints["dspace_ucaldas"]["ror"] = "https://ror.org/049n68p64"
endpoints["dspace_ucaldas"]["url"] = "https://repositorio.ucaldas.edu.co/server/oai/request"
endpoints["dspace_ucaldas"]["metadataPrefix"] = "dim"
endpoints["dspace_ucaldas"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucaldas"]["checkpoint"] = {}
endpoints["dspace_ucaldas"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucaldas"]["checkpoint"]["selective"] = False
endpoints["dspace_ucaldas"]["checkpoint"]["days"] = 30
endpoints["dspace_unicordoba"] = {}
endpoints["dspace_unicordoba"]["enabled"] = True
endpoints["dspace_unicordoba"]["name"] = "UNIVERSIDAD DE CORDOBA"
endpoints["dspace_unicordoba"]["ror"] = "https://ror.org/04nmbd607"
endpoints["dspace_unicordoba"]["url"] = "https://repositorio.unicordoba.edu.co/server/oai/request"
endpoints["dspace_unicordoba"]["metadataPrefix"] = "dim"
endpoints["dspace_unicordoba"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unicordoba"]["checkpoint"] = {}
endpoints["dspace_unicordoba"]["checkpoint"]["enabled"] = True
endpoints["dspace_unicordoba"]["checkpoint"]["selective"] = False
endpoints["dspace_unicordoba"]["checkpoint"]["days"] = 30
endpoints["dspace_minciencias"] = {}
endpoints["dspace_minciencias"]["enabled"] = True
endpoints["dspace_minciencias"]["name"] = "UNIVERSIDAD SURCOLOMBIANA"
endpoints["dspace_minciencias"]["ror"] = "https://ror.org/04s60rj63"
endpoints["dspace_minciencias"]["url"] = "https://repositorio.minciencias.gov.co/server/oai/request"
endpoints["dspace_minciencias"]["metadataPrefix"] = "dim"
endpoints["dspace_minciencias"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_minciencias"]["checkpoint"] = {}
endpoints["dspace_minciencias"]["checkpoint"]["enabled"] = True
endpoints["dspace_minciencias"]["checkpoint"]["selective"] = False
endpoints["dspace_minciencias"]["checkpoint"]["days"] = 30
endpoints["dspace_unimilitar"] = {}
endpoints["dspace_unimilitar"]["enabled"] = True
endpoints["dspace_unimilitar"]["name"] = "UNIVERSIDAD MILITAR-NUEVA GRANADA"
endpoints["dspace_unimilitar"]["ror"] = "https://ror.org/05n0gsn30"
endpoints["dspace_unimilitar"]["url"] = "https://repository.unimilitar.edu.co/server/oai/request"
endpoints["dspace_unimilitar"]["metadataPrefix"] = "dim"
endpoints["dspace_unimilitar"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unimilitar"]["checkpoint"] = {}
endpoints["dspace_unimilitar"]["checkpoint"]["enabled"] = True
endpoints["dspace_unimilitar"]["checkpoint"]["selective"] = False
endpoints["dspace_unimilitar"]["checkpoint"]["days"] = 30
endpoints["dspace_unillanos"] = {}
endpoints["dspace_unillanos"]["enabled"] = True
endpoints["dspace_unillanos"]["name"] = "UNIVERSIDAD DE LOS LLANOS"
endpoints["dspace_unillanos"]["ror"] = "https://ror.org/042335e16"
endpoints["dspace_unillanos"]["url"] = "https://repositorio.unillanos.edu.co/server/oai/request"
endpoints["dspace_unillanos"]["metadataPrefix"] = "dim"
endpoints["dspace_unillanos"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unillanos"]["checkpoint"] = {}
endpoints["dspace_unillanos"]["checkpoint"]["enabled"] = True
endpoints["dspace_unillanos"]["checkpoint"]["selective"] = False
endpoints["dspace_unillanos"]["checkpoint"]["days"] = 30
endpoints["dspace_unicolmayor"] = {}
endpoints["dspace_unicolmayor"]["enabled"] = True
endpoints["dspace_unicolmayor"]["name"] = "UNIVERSIDAD-COLEGIO MAYOR DE CUNDINAMARCA"
endpoints["dspace_unicolmayor"]["ror"] = "https://ror.org/055mabf46"
endpoints["dspace_unicolmayor"]["url"] = "https://repositorio.unicolmayor.edu.co/oai/request"
endpoints["dspace_unicolmayor"]["metadataPrefix"] = "dim"
endpoints["dspace_unicolmayor"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unicolmayor"]["checkpoint"] = {}
endpoints["dspace_unicolmayor"]["checkpoint"]["enabled"] = True
endpoints["dspace_unicolmayor"]["checkpoint"]["selective"] = False
endpoints["dspace_unicolmayor"]["checkpoint"]["days"] = 30
endpoints["dspace_unipacifico"] = {}
endpoints["dspace_unipacifico"]["enabled"] = True
endpoints["dspace_unipacifico"]["name"] = "UNIVERSIDAD DEL PACIFICO"
endpoints["dspace_unipacifico"]["ror"] = "https://ror.org/05ma4gw77"
endpoints["dspace_unipacifico"]["url"] = "https://repositorio.unipacifico.edu.co/oai/request"
endpoints["dspace_unipacifico"]["metadataPrefix"] = "dim"
endpoints["dspace_unipacifico"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unipacifico"]["checkpoint"] = {}
endpoints["dspace_unipacifico"]["checkpoint"]["enabled"] = True
endpoints["dspace_unipacifico"]["checkpoint"]["selective"] = False
endpoints["dspace_unipacifico"]["checkpoint"]["days"] = 30
endpoints["dspace_udea"] = {}
endpoints["dspace_udea"]["enabled"] = True
endpoints["dspace_udea"]["name"] = "UNIVERSIDAD DE ANTIOQUIA"
endpoints["dspace_udea"]["ror"] = "https://ror.org/03bp5hc83"
endpoints["dspace_udea"]["url"] = "https://bibliotecadigital.udea.edu.co/oai/request"
endpoints["dspace_udea"]["metadataPrefix"] = "dim"
endpoints["dspace_udea"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_udea"]["checkpoint"] = {}
endpoints["dspace_udea"]["checkpoint"]["enabled"] = True
endpoints["dspace_udea"]["checkpoint"]["selective"] = False
endpoints["dspace_udea"]["checkpoint"]["days"] = 30
endpoints["dspace_uac"] = {}
endpoints["dspace_uac"]["enabled"] = True
endpoints["dspace_uac"]["name"] = "UNIVERSIDAD DEL ATLANTICO"
endpoints["dspace_uac"]["ror"] = "https://ror.org/01pe78696"
endpoints["dspace_uac"]["url"] = "http://repositorio.uac.edu.co/oai/request"
endpoints["dspace_uac"]["metadataPrefix"] = "dim"
endpoints["dspace_uac"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uac"]["checkpoint"] = {}
endpoints["dspace_uac"]["checkpoint"]["enabled"] = True
endpoints["dspace_uac"]["checkpoint"]["selective"] = False
endpoints["dspace_uac"]["checkpoint"]["days"] = 30
endpoints["dspace_univalle"] = {}
endpoints["dspace_univalle"]["enabled"] = True
endpoints["dspace_univalle"]["name"] = "UNIVERSIDAD DEL VALLE"
endpoints["dspace_univalle"]["ror"] = "https://ror.org/02xw8cw23"
endpoints["dspace_univalle"]["url"] = "https://bibliotecadigital.univalle.edu.co/server/oai/request"
endpoints["dspace_univalle"]["metadataPrefix"] = "dim"
endpoints["dspace_univalle"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_univalle"]["checkpoint"] = {}
endpoints["dspace_univalle"]["checkpoint"]["enabled"] = True
endpoints["dspace_univalle"]["checkpoint"]["selective"] = False
endpoints["dspace_univalle"]["checkpoint"]["days"] = 30
endpoints["dspace_uis"] = {}
endpoints["dspace_uis"]["enabled"] = True
endpoints["dspace_uis"]["name"] = "UNIVERSIDAD INDUSTRIAL DE SANTANDER"
endpoints["dspace_uis"]["ror"] = "https://ror.org/00xc1d948"
endpoints["dspace_uis"]["url"] = "https://noesis.uis.edu.co/server/oai/request"
endpoints["dspace_uis"]["metadataPrefix"] = "dim"
endpoints["dspace_uis"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uis"]["checkpoint"] = {}
endpoints["dspace_uis"]["checkpoint"]["enabled"] = True
endpoints["dspace_uis"]["checkpoint"]["selective"] = False
endpoints["dspace_uis"]["checkpoint"]["days"] = 30
endpoints["dspace_unicartagena"] = {}
endpoints["dspace_unicartagena"]["enabled"] = True
endpoints["dspace_unicartagena"]["name"] = "UNIVERSIDAD DE CARTAGENA"
endpoints["dspace_unicartagena"]["ror"] = "https://ror.org/0409zd934"
endpoints["dspace_unicartagena"]["url"] = (
    "https://repositorio.unicartagena.edu.co/server/oai/request"
)
endpoints["dspace_unicartagena"]["metadataPrefix"] = "dim"
endpoints["dspace_unicartagena"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unicartagena"]["checkpoint"] = {}
endpoints["dspace_unicartagena"]["checkpoint"]["enabled"] = True
endpoints["dspace_unicartagena"]["checkpoint"]["selective"] = False
endpoints["dspace_unicartagena"]["checkpoint"]["days"] = 30
endpoints["dspace_ut"] = {}
endpoints["dspace_ut"]["enabled"] = True
endpoints["dspace_ut"]["name"] = "UNIVERSIDAD DEL TOLIMA"
endpoints["dspace_ut"]["ror"] = "https://ror.org/011bqgx84"
endpoints["dspace_ut"]["url"] = "https://repository.ut.edu.co/server/oai/request"
endpoints["dspace_ut"]["metadataPrefix"] = "dim"
endpoints["dspace_ut"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ut"]["checkpoint"] = {}
endpoints["dspace_ut"]["checkpoint"]["enabled"] = True
endpoints["dspace_ut"]["checkpoint"]["selective"] = False
endpoints["dspace_ut"]["checkpoint"]["days"] = 30
endpoints["dspace_uniquindio"] = {}
endpoints["dspace_uniquindio"]["enabled"] = True
endpoints["dspace_uniquindio"]["name"] = "UNIVERSIDAD DEL QUINDIO"
endpoints["dspace_uniquindio"]["ror"] = "https://ror.org/01358s213"
endpoints["dspace_uniquindio"]["url"] = "https://bdigital.uniquindio.edu.co/server/oai/request"
endpoints["dspace_uniquindio"]["metadataPrefix"] = "dim"
endpoints["dspace_uniquindio"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniquindio"]["checkpoint"] = {}
endpoints["dspace_uniquindio"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniquindio"]["checkpoint"]["selective"] = False
endpoints["dspace_uniquindio"]["checkpoint"]["days"] = 30
endpoints["dspace_ufps"] = {}
endpoints["dspace_ufps"]["enabled"] = True
endpoints["dspace_ufps"]["name"] = "UNIVERSIDAD FRANCISCO DE PAULA SANTANDER"
endpoints["dspace_ufps"]["ror"] = "https://ror.org/01vwm8t51"
endpoints["dspace_ufps"]["url"] = "https://repositorio.ufps.edu.co/oai/request"
endpoints["dspace_ufps"]["metadataPrefix"] = "dim"
endpoints["dspace_ufps"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ufps"]["checkpoint"] = {}
endpoints["dspace_ufps"]["checkpoint"]["enabled"] = True
endpoints["dspace_ufps"]["checkpoint"]["selective"] = False
endpoints["dspace_ufps"]["checkpoint"]["days"] = 30
endpoints["dspace_ucundinamarca"] = {}
endpoints["dspace_ucundinamarca"]["enabled"] = True
endpoints["dspace_ucundinamarca"]["name"] = "UNIVERSIDAD DE CUNDINAMARCA-UDEC"
endpoints["dspace_ucundinamarca"]["ror"] = "https://ror.org/040tqqd15"
endpoints["dspace_ucundinamarca"]["url"] = (
    "https://repositorio.ucundinamarca.edu.co/server/oai/request"
)
endpoints["dspace_ucundinamarca"]["metadataPrefix"] = "dim"
endpoints["dspace_ucundinamarca"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucundinamarca"]["checkpoint"] = {}
endpoints["dspace_ucundinamarca"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucundinamarca"]["checkpoint"]["selective"] = False
endpoints["dspace_ucundinamarca"]["checkpoint"]["days"] = 30
endpoints["dspace_unisucre"] = {}
endpoints["dspace_unisucre"]["enabled"] = True
endpoints["dspace_unisucre"]["name"] = "UNIVERSIDAD DE SUCRE"
endpoints["dspace_unisucre"]["ror"] = "https://ror.org/04fbb7514"
endpoints["dspace_unisucre"]["url"] = "https://repositorio.unisucre.edu.co/server/oai/request"
endpoints["dspace_unisucre"]["metadataPrefix"] = "dim"
endpoints["dspace_unisucre"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unisucre"]["checkpoint"] = {}
endpoints["dspace_unisucre"]["checkpoint"]["enabled"] = True
endpoints["dspace_unisucre"]["checkpoint"]["selective"] = False
endpoints["dspace_unisucre"]["checkpoint"]["days"] = 30
endpoints["dspace_uniguajira"] = {}
endpoints["dspace_uniguajira"]["enabled"] = True
endpoints["dspace_uniguajira"]["name"] = "UNIVERSIDAD DE LA GUAJIRA"
endpoints["dspace_uniguajira"]["ror"] = "https://ror.org/04cjjhh62"
endpoints["dspace_uniguajira"]["url"] = (
    "https://repositoryinst.uniguajira.edu.co/server/oai/request"
)
endpoints["dspace_uniguajira"]["metadataPrefix"] = "dim"
endpoints["dspace_uniguajira"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniguajira"]["checkpoint"] = {}
endpoints["dspace_uniguajira"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniguajira"]["checkpoint"]["selective"] = False
endpoints["dspace_uniguajira"]["checkpoint"]["days"] = 30
endpoints["dspace_udistrital"] = {}
endpoints["dspace_udistrital"]["enabled"] = True
endpoints["dspace_udistrital"]["name"] = "UNIVERSIDAD DISTRITAL-FRANCISCO JOSE DE CALDAS"
endpoints["dspace_udistrital"]["ror"] = "https://ror.org/02jsxd428"
endpoints["dspace_udistrital"]["url"] = "https://repository.udistrital.edu.co/server/oai/request"
endpoints["dspace_udistrital"]["metadataPrefix"] = "dim"
endpoints["dspace_udistrital"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_udistrital"]["checkpoint"] = {}
endpoints["dspace_udistrital"]["checkpoint"]["enabled"] = True
endpoints["dspace_udistrital"]["checkpoint"]["selective"] = False
endpoints["dspace_udistrital"]["checkpoint"]["days"] = 30
endpoints["dspace_javeriana"] = {}
endpoints["dspace_javeriana"]["enabled"] = True
endpoints["dspace_javeriana"]["name"] = "PONTIFICIA UNIVERSIDAD JAVERIANA"
endpoints["dspace_javeriana"]["ror"] = "https://ror.org/03etyjw28"
endpoints["dspace_javeriana"]["url"] = "https://repository.javeriana.edu.co/oai/request"
endpoints["dspace_javeriana"]["metadataPrefix"] = "dim"
endpoints["dspace_javeriana"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_javeriana"]["checkpoint"] = {}
endpoints["dspace_javeriana"]["checkpoint"]["enabled"] = True
endpoints["dspace_javeriana"]["checkpoint"]["selective"] = False
endpoints["dspace_javeriana"]["checkpoint"]["days"] = 30
endpoints["dspace_car"] = {}
endpoints["dspace_car"]["enabled"] = True
endpoints["dspace_car"]["name"] = "UNIVERSIDAD INCCA DE COLOMBIA"
endpoints["dspace_car"]["ror"] = "https://ror.org/000xmhb57"
endpoints["dspace_car"]["url"] = "https://sie.car.gov.co/server/oai/request"
endpoints["dspace_car"]["metadataPrefix"] = "dim"
endpoints["dspace_car"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_car"]["checkpoint"] = {}
endpoints["dspace_car"]["checkpoint"]["enabled"] = True
endpoints["dspace_car"]["checkpoint"]["selective"] = False
endpoints["dspace_car"]["checkpoint"]["days"] = 30
endpoints["dspace_usta"] = {}
endpoints["dspace_usta"]["enabled"] = True
endpoints["dspace_usta"]["name"] = "UNIVERSIDAD SANTO TOMAS"
endpoints["dspace_usta"]["ror"] = "https://ror.org/02vbtzd72"
endpoints["dspace_usta"]["url"] = "https://repository.usta.edu.co/oai/request"
endpoints["dspace_usta"]["metadataPrefix"] = "dim"
endpoints["dspace_usta"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_usta"]["checkpoint"] = {}
endpoints["dspace_usta"]["checkpoint"]["enabled"] = True
endpoints["dspace_usta"]["checkpoint"]["selective"] = False
endpoints["dspace_usta"]["checkpoint"]["days"] = 30
endpoints["dspace_uexternado"] = {}
endpoints["dspace_uexternado"]["enabled"] = True
endpoints["dspace_uexternado"]["name"] = "UNIVERSIDAD EXTERNADO DE COLOMBIA"
endpoints["dspace_uexternado"]["ror"] = "https://ror.org/02xtwpk10"
endpoints["dspace_uexternado"]["url"] = "https://bdigital.uexternado.edu.co/server/oai/request"
endpoints["dspace_uexternado"]["metadataPrefix"] = "dim"
endpoints["dspace_uexternado"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uexternado"]["checkpoint"] = {}
endpoints["dspace_uexternado"]["checkpoint"]["enabled"] = True
endpoints["dspace_uexternado"]["checkpoint"]["selective"] = False
endpoints["dspace_uexternado"]["checkpoint"]["days"] = 30
endpoints["dspace_utadeo"] = {}
endpoints["dspace_utadeo"]["enabled"] = True
endpoints["dspace_utadeo"]["name"] = "FUNDACION UNIVERSIDAD DE BOGOTA - JORGE TADEO LOZANO"
endpoints["dspace_utadeo"]["ror"] = "https://ror.org/04wbzgn90"
endpoints["dspace_utadeo"]["url"] = "https://expeditiorepositorio.utadeo.edu.co/oai/request"
endpoints["dspace_utadeo"]["metadataPrefix"] = "dim"
endpoints["dspace_utadeo"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_utadeo"]["checkpoint"] = {}
endpoints["dspace_utadeo"]["checkpoint"]["enabled"] = True
endpoints["dspace_utadeo"]["checkpoint"]["selective"] = False
endpoints["dspace_utadeo"]["checkpoint"]["days"] = 30
endpoints["dspace_upb"] = {}
endpoints["dspace_upb"]["enabled"] = True
endpoints["dspace_upb"]["name"] = "UNIVERSIDAD PONTIFICIA BOLIVARIANA"
endpoints["dspace_upb"]["ror"] = "https://ror.org/02dxm8k93"
endpoints["dspace_upb"]["url"] = "https://repository.upb.edu.co/oai/request"
endpoints["dspace_upb"]["metadataPrefix"] = "dim"
endpoints["dspace_upb"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_upb"]["checkpoint"] = {}
endpoints["dspace_upb"]["checkpoint"]["enabled"] = True
endpoints["dspace_upb"]["checkpoint"]["selective"] = False
endpoints["dspace_upb"]["checkpoint"]["days"] = 30
endpoints["dspace_unisabana"] = {}
endpoints["dspace_unisabana"]["enabled"] = True
endpoints["dspace_unisabana"]["name"] = "UNIVERSIDAD DE LA SABANA"
endpoints["dspace_unisabana"]["ror"] = "https://ror.org/02sqgkj21"
endpoints["dspace_unisabana"]["url"] = "https://intellectum.unisabana.edu.co/oai/request"
endpoints["dspace_unisabana"]["metadataPrefix"] = "dim"
endpoints["dspace_unisabana"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unisabana"]["checkpoint"] = {}
endpoints["dspace_unisabana"]["checkpoint"]["enabled"] = True
endpoints["dspace_unisabana"]["checkpoint"]["selective"] = False
endpoints["dspace_unisabana"]["checkpoint"]["days"] = 30
endpoints["dspace_eafit"] = {}
endpoints["dspace_eafit"]["enabled"] = True
endpoints["dspace_eafit"]["name"] = "UNIVERSIDAD EAFIT-"
endpoints["dspace_eafit"]["ror"] = "https://ror.org/03y3y9v44"
endpoints["dspace_eafit"]["url"] = "https://repository.eafit.edu.co/server/oai/request"
endpoints["dspace_eafit"]["metadataPrefix"] = "dim"
endpoints["dspace_eafit"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_eafit"]["checkpoint"] = {}
endpoints["dspace_eafit"]["checkpoint"]["enabled"] = True
endpoints["dspace_eafit"]["checkpoint"]["selective"] = False
endpoints["dspace_eafit"]["checkpoint"]["days"] = 30
endpoints["dspace_uninorte"] = {}
endpoints["dspace_uninorte"]["enabled"] = True
endpoints["dspace_uninorte"]["name"] = "UNIVERSIDAD DEL NORTE"
endpoints["dspace_uninorte"]["ror"] = "https://ror.org/031e6xm45"
endpoints["dspace_uninorte"]["url"] = "https://manglar.uninorte.edu.co/oai/request"
endpoints["dspace_uninorte"]["metadataPrefix"] = "dim"
endpoints["dspace_uninorte"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uninorte"]["checkpoint"] = {}
endpoints["dspace_uninorte"]["checkpoint"]["enabled"] = True
endpoints["dspace_uninorte"]["checkpoint"]["selective"] = False
endpoints["dspace_uninorte"]["checkpoint"]["days"] = 30
endpoints["dspace_urosario"] = {}
endpoints["dspace_urosario"]["enabled"] = True
endpoints["dspace_urosario"]["name"] = "Universidad del Rosario"
endpoints["dspace_urosario"]["ror"] = "https://ror.org/0108mwc04"
endpoints["dspace_urosario"]["url"] = "https://repository.urosario.edu.co/server/oai/request"
endpoints["dspace_urosario"]["metadataPrefix"] = "dim"
endpoints["dspace_urosario"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_urosario"]["checkpoint"] = {}
endpoints["dspace_urosario"]["checkpoint"]["enabled"] = True
endpoints["dspace_urosario"]["checkpoint"]["selective"] = False
endpoints["dspace_urosario"]["checkpoint"]["days"] = 30
endpoints["dspace_uamerica"] = {}
endpoints["dspace_uamerica"]["enabled"] = True
endpoints["dspace_uamerica"]["name"] = "FUNDACION UNIVERSIDAD DE AMERICA"
endpoints["dspace_uamerica"]["ror"] = "https://ror.org/00kcjks51"
endpoints["dspace_uamerica"]["url"] = "https://repository.uamerica.edu.co/server/oai/request"
endpoints["dspace_uamerica"]["metadataPrefix"] = "dim"
endpoints["dspace_uamerica"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uamerica"]["checkpoint"] = {}
endpoints["dspace_uamerica"]["checkpoint"]["enabled"] = True
endpoints["dspace_uamerica"]["checkpoint"]["selective"] = False
endpoints["dspace_uamerica"]["checkpoint"]["days"] = 30
endpoints["dspace_usb"] = {}
endpoints["dspace_usb"]["enabled"] = True
endpoints["dspace_usb"]["name"] = "UNIVERSIDAD DE SAN BUENAVENTURA"
endpoints["dspace_usb"]["ror"] = "https://ror.org/04sqpjb51"
endpoints["dspace_usb"]["url"] = "https://bibliotecadigital.usb.edu.co/server/oai/request"
endpoints["dspace_usb"]["metadataPrefix"] = "dim"
endpoints["dspace_usb"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_usb"]["checkpoint"] = {}
endpoints["dspace_usb"]["checkpoint"]["enabled"] = True
endpoints["dspace_usb"]["checkpoint"]["selective"] = False
endpoints["dspace_usb"]["checkpoint"]["days"] = 30
endpoints["dspace_ucatolica"] = {}
endpoints["dspace_ucatolica"]["enabled"] = True
endpoints["dspace_ucatolica"]["name"] = "UNIVERSIDAD CATOLICA DE COLOMBIA"
endpoints["dspace_ucatolica"]["ror"] = "https://ror.org/01scwqh06"
endpoints["dspace_ucatolica"]["url"] = "https://repository.ucatolica.edu.co/server/oai/request"
endpoints["dspace_ucatolica"]["metadataPrefix"] = "dim"
endpoints["dspace_ucatolica"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucatolica"]["checkpoint"] = {}
endpoints["dspace_ucatolica"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucatolica"]["checkpoint"]["selective"] = False
endpoints["dspace_ucatolica"]["checkpoint"]["days"] = 30
endpoints["dspace_umariana"] = {}
endpoints["dspace_umariana"]["enabled"] = True
endpoints["dspace_umariana"]["name"] = "UNIVERSIDAD MARIANA"
endpoints["dspace_umariana"]["ror"] = "https://ror.org/00ct7kr02"
endpoints["dspace_umariana"]["url"] = "https://repositorio.umariana.edu.co/oai/request"
endpoints["dspace_umariana"]["metadataPrefix"] = "dim"
endpoints["dspace_umariana"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_umariana"]["checkpoint"] = {}
endpoints["dspace_umariana"]["checkpoint"]["enabled"] = True
endpoints["dspace_umariana"]["checkpoint"]["selective"] = False
endpoints["dspace_umariana"]["checkpoint"]["days"] = 30
endpoints["dspace_umanizales"] = {}
endpoints["dspace_umanizales"]["enabled"] = True
endpoints["dspace_umanizales"]["name"] = "UNIVERSIDAD DE MANIZALES"
endpoints["dspace_umanizales"]["ror"] = "https://ror.org/031n6w191"
endpoints["dspace_umanizales"]["url"] = "https://ridum.umanizales.edu.co/oai/request"
endpoints["dspace_umanizales"]["metadataPrefix"] = "dim"
endpoints["dspace_umanizales"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_umanizales"]["checkpoint"] = {}
endpoints["dspace_umanizales"]["checkpoint"]["enabled"] = True
endpoints["dspace_umanizales"]["checkpoint"]["selective"] = False
endpoints["dspace_umanizales"]["checkpoint"]["days"] = 30
endpoints["dspace_uco"] = {}
endpoints["dspace_uco"]["enabled"] = True
endpoints["dspace_uco"]["name"] = "UNIVERSIDAD CATOLICA DE ORIENTE -UCO"
endpoints["dspace_uco"]["ror"] = "https://ror.org/02pzxyp49"
endpoints["dspace_uco"]["url"] = "https://repositorio.uco.edu.co/server/oai/request"
endpoints["dspace_uco"]["metadataPrefix"] = "dim"
endpoints["dspace_uco"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uco"]["checkpoint"] = {}
endpoints["dspace_uco"]["checkpoint"]["enabled"] = True
endpoints["dspace_uco"]["checkpoint"]["selective"] = False
endpoints["dspace_uco"]["checkpoint"]["days"] = 30
endpoints["dspace_usergioarboleda"] = {}
endpoints["dspace_usergioarboleda"]["enabled"] = True
endpoints["dspace_usergioarboleda"]["name"] = "UNIVERSIDAD SERGIO ARBOLEDA"
endpoints["dspace_usergioarboleda"]["ror"] = "https://ror.org/02ckere89"
endpoints["dspace_usergioarboleda"]["url"] = "https://repository.usergioarboleda.edu.co/oai/request"
endpoints["dspace_usergioarboleda"]["metadataPrefix"] = "dim"
endpoints["dspace_usergioarboleda"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_usergioarboleda"]["checkpoint"] = {}
endpoints["dspace_usergioarboleda"]["checkpoint"]["enabled"] = True
endpoints["dspace_usergioarboleda"]["checkpoint"]["selective"] = False
endpoints["dspace_usergioarboleda"]["checkpoint"]["days"] = 30
endpoints["dspace_unbosque"] = {}
endpoints["dspace_unbosque"]["enabled"] = True
endpoints["dspace_unbosque"]["name"] = "UNIVERSIDAD EL BOSQUE"
endpoints["dspace_unbosque"]["ror"] = "https://ror.org/04m9gzq43"
endpoints["dspace_unbosque"]["url"] = "https://repositorio.unbosque.edu.co/server/oai/request"
endpoints["dspace_unbosque"]["metadataPrefix"] = "dim"
endpoints["dspace_unbosque"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unbosque"]["checkpoint"] = {}
endpoints["dspace_unbosque"]["checkpoint"]["enabled"] = True
endpoints["dspace_unbosque"]["checkpoint"]["selective"] = False
endpoints["dspace_unbosque"]["checkpoint"]["days"] = 30
endpoints["dspace_uniboyaca"] = {}
endpoints["dspace_uniboyaca"]["enabled"] = True
endpoints["dspace_uniboyaca"]["name"] = "UNIVERSIDAD DE BOYACA UNIBOYACA"
endpoints["dspace_uniboyaca"]["ror"] = "https://ror.org/042ewz993"
endpoints["dspace_uniboyaca"]["url"] = "https://repositorio.uniboyaca.edu.co/oai/request"
endpoints["dspace_uniboyaca"]["metadataPrefix"] = "dim"
endpoints["dspace_uniboyaca"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniboyaca"]["checkpoint"] = {}
endpoints["dspace_uniboyaca"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniboyaca"]["checkpoint"]["selective"] = False
endpoints["dspace_uniboyaca"]["checkpoint"]["days"] = 30
endpoints["dspace_ugc"] = {}
endpoints["dspace_ugc"]["enabled"] = True
endpoints["dspace_ugc"]["name"] = "UNIVERSIDAD LA GRAN COLOMBIA"
endpoints["dspace_ugc"]["ror"] = "https://ror.org/01r5afm23"
endpoints["dspace_ugc"]["url"] = "https://repository.ugc.edu.co/server/oai/request"
endpoints["dspace_ugc"]["metadataPrefix"] = "dim"
endpoints["dspace_ugc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ugc"]["checkpoint"] = {}
endpoints["dspace_ugc"]["checkpoint"]["enabled"] = True
endpoints["dspace_ugc"]["checkpoint"]["selective"] = False
endpoints["dspace_ugc"]["checkpoint"]["days"] = 30
endpoints["dspace_lasalle"] = {}
endpoints["dspace_lasalle"]["enabled"] = True
endpoints["dspace_lasalle"]["name"] = "UNIVERSIDAD DE LA SALLE"
endpoints["dspace_lasalle"]["ror"] = "https://ror.org/02beve479"
endpoints["dspace_lasalle"]["url"] = "https://ciencia.lasalle.edu.co/server/oai/request"
endpoints["dspace_lasalle"]["metadataPrefix"] = "dim"
endpoints["dspace_lasalle"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_lasalle"]["checkpoint"] = {}
endpoints["dspace_lasalle"]["checkpoint"]["enabled"] = True
endpoints["dspace_lasalle"]["checkpoint"]["selective"] = False
endpoints["dspace_lasalle"]["checkpoint"]["days"] = 30
endpoints["dspace_usc"] = {}
endpoints["dspace_usc"]["enabled"] = True
endpoints["dspace_usc"]["name"] = "UNIVERSIDAD SANTIAGO DE CALI"
endpoints["dspace_usc"]["ror"] = "https://ror.org/00dxj9a45"
endpoints["dspace_usc"]["url"] = "https://repositorio.usc.edu.co/server/oai/request"
endpoints["dspace_usc"]["metadataPrefix"] = "dim"
endpoints["dspace_usc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_usc"]["checkpoint"] = {}
endpoints["dspace_usc"]["checkpoint"]["enabled"] = True
endpoints["dspace_usc"]["checkpoint"]["selective"] = False
endpoints["dspace_usc"]["checkpoint"]["days"] = 30
endpoints["dspace_udem"] = {}
endpoints["dspace_udem"]["enabled"] = True
endpoints["dspace_udem"]["name"] = "UNIVERSIDAD DE MEDELLIN"
endpoints["dspace_udem"]["ror"] = "https://ror.org/030kw0b65"
endpoints["dspace_udem"]["url"] = "https://repository.udem.edu.co/oai/request"
endpoints["dspace_udem"]["metadataPrefix"] = "dim"
endpoints["dspace_udem"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_udem"]["checkpoint"] = {}
endpoints["dspace_udem"]["checkpoint"]["enabled"] = True
endpoints["dspace_udem"]["checkpoint"]["selective"] = False
endpoints["dspace_udem"]["checkpoint"]["days"] = 30
endpoints["dspace_uniandes"] = {}
endpoints["dspace_uniandes"]["enabled"] = True
endpoints["dspace_uniandes"]["name"] = "UNIVERSIDAD DE LOS ANDES"
endpoints["dspace_uniandes"]["ror"] = "https://ror.org/02h1b1x27"
endpoints["dspace_uniandes"]["url"] = "https://repositorio.uniandes.edu.co/server/oai/request"
endpoints["dspace_uniandes"]["metadataPrefix"] = "dim"
endpoints["dspace_uniandes"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniandes"]["checkpoint"] = {}
endpoints["dspace_uniandes"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniandes"]["checkpoint"]["selective"] = False
endpoints["dspace_uniandes"]["checkpoint"]["days"] = 30
endpoints["dspace_unipiloto"] = {}
endpoints["dspace_unipiloto"]["enabled"] = True
endpoints["dspace_unipiloto"]["name"] = "CORPORACION UNIVERSIDAD PILOTO DE COLOMBIA"
endpoints["dspace_unipiloto"]["ror"] = "https://ror.org/03m5f7m65"
endpoints["dspace_unipiloto"]["url"] = "https://repository.unipiloto.edu.co/oai/request"
endpoints["dspace_unipiloto"]["metadataPrefix"] = "dim"
endpoints["dspace_unipiloto"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unipiloto"]["checkpoint"] = {}
endpoints["dspace_unipiloto"]["checkpoint"]["enabled"] = True
endpoints["dspace_unipiloto"]["checkpoint"]["selective"] = False
endpoints["dspace_unipiloto"]["checkpoint"]["days"] = 30
endpoints["dspace_ucc"] = {}
endpoints["dspace_ucc"]["enabled"] = True
endpoints["dspace_ucc"]["name"] = "UNIVERSIDAD COOPERATIVA DE COLOMBIA"
endpoints["dspace_ucc"]["ror"] = "https://ror.org/04td15k45"
endpoints["dspace_ucc"]["url"] = "https://repository.ucc.edu.co/server/oai/request"
endpoints["dspace_ucc"]["metadataPrefix"] = "dim"
endpoints["dspace_ucc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucc"]["checkpoint"] = {}
endpoints["dspace_ucc"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucc"]["checkpoint"]["selective"] = False
endpoints["dspace_ucc"]["checkpoint"]["days"] = 30
endpoints["dspace_unab"] = {}
endpoints["dspace_unab"]["enabled"] = True
endpoints["dspace_unab"]["name"] = "UNIVERSIDAD AUTONOMA DE BUCARAMANGA-UNAB-"
endpoints["dspace_unab"]["ror"] = "https://ror.org/00gkhpw57"
endpoints["dspace_unab"]["url"] = "https://repository.unab.edu.co/oai/request"
endpoints["dspace_unab"]["metadataPrefix"] = "dim"
endpoints["dspace_unab"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unab"]["checkpoint"] = {}
endpoints["dspace_unab"]["checkpoint"]["enabled"] = True
endpoints["dspace_unab"]["checkpoint"]["selective"] = False
endpoints["dspace_unab"]["checkpoint"]["days"] = 30
endpoints["dspace_ibero"] = {}
endpoints["dspace_ibero"]["enabled"] = True
endpoints["dspace_ibero"]["name"] = "UNIVERSIDAD METROPOLITANA"
endpoints["dspace_ibero"]["ror"] = "https://ror.org/00cey1j90"
endpoints["dspace_ibero"]["url"] = "https://repositorio.ibero.edu.co/server/oai/request"
endpoints["dspace_ibero"]["metadataPrefix"] = "dim"
endpoints["dspace_ibero"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ibero"]["checkpoint"] = {}
endpoints["dspace_ibero"]["checkpoint"]["enabled"] = True
endpoints["dspace_ibero"]["checkpoint"]["selective"] = False
endpoints["dspace_ibero"]["checkpoint"]["days"] = 30
endpoints["dspace_autonoma"] = {}
endpoints["dspace_autonoma"]["enabled"] = True
endpoints["dspace_autonoma"]["name"] = "UNIVERSIDAD AUTONOMA DE MANIZALES"
endpoints["dspace_autonoma"]["ror"] = "https://ror.org/00jfare13"
endpoints["dspace_autonoma"]["url"] = "https://repositorio.autonoma.edu.co/server/oai/request"
endpoints["dspace_autonoma"]["metadataPrefix"] = "dim"
endpoints["dspace_autonoma"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_autonoma"]["checkpoint"] = {}
endpoints["dspace_autonoma"]["checkpoint"]["enabled"] = True
endpoints["dspace_autonoma"]["checkpoint"]["selective"] = False
endpoints["dspace_autonoma"]["checkpoint"]["days"] = 30
endpoints["dspace_ucm"] = {}
endpoints["dspace_ucm"]["enabled"] = True
endpoints["dspace_ucm"]["name"] = "UNIVERSIDAD CATOLICA DE MANIZALES"
endpoints["dspace_ucm"]["ror"] = "https://ror.org/05kaxtp50"
endpoints["dspace_ucm"]["url"] = "https://repositorio.ucm.edu.co/oai/request"
endpoints["dspace_ucm"]["metadataPrefix"] = "dim"
endpoints["dspace_ucm"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucm"]["checkpoint"] = {}
endpoints["dspace_ucm"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucm"]["checkpoint"]["selective"] = False
endpoints["dspace_ucm"]["checkpoint"]["days"] = 30
endpoints["dspace_icesi"] = {}
endpoints["dspace_icesi"]["enabled"] = True
endpoints["dspace_icesi"]["name"] = "UNIVERSIDAD ICESI"
endpoints["dspace_icesi"]["ror"] = "https://ror.org/02t54e151"
endpoints["dspace_icesi"]["url"] = "https://repository.icesi.edu.co/server/oai/request"
endpoints["dspace_icesi"]["metadataPrefix"] = "dim"
endpoints["dspace_icesi"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_icesi"]["checkpoint"] = {}
endpoints["dspace_icesi"]["checkpoint"]["enabled"] = True
endpoints["dspace_icesi"]["checkpoint"]["selective"] = False
endpoints["dspace_icesi"]["checkpoint"]["days"] = 30
endpoints["dspace_uao"] = {}
endpoints["dspace_uao"]["enabled"] = True
endpoints["dspace_uao"]["name"] = "UNIVERSIDAD AUTONOMA DE OCCIDENTE"
endpoints["dspace_uao"]["ror"] = "https://ror.org/02drkkh02"
endpoints["dspace_uao"]["url"] = "https://red.uao.edu.co/server/oai/request"
endpoints["dspace_uao"]["metadataPrefix"] = "dim"
endpoints["dspace_uao"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uao"]["checkpoint"] = {}
endpoints["dspace_uao"]["checkpoint"]["enabled"] = True
endpoints["dspace_uao"]["checkpoint"]["selective"] = False
endpoints["dspace_uao"]["checkpoint"]["days"] = 30
endpoints["dspace_unibague"] = {}
endpoints["dspace_unibague"]["enabled"] = True
endpoints["dspace_unibague"]["name"] = "UNIVERSIDAD DE IBAGUE"
endpoints["dspace_unibague"]["ror"] = "https://ror.org/04pzf5g91"
endpoints["dspace_unibague"]["url"] = "https://repositorio.unibague.edu.co/server/oai/request"
endpoints["dspace_unibague"]["metadataPrefix"] = "dim"
endpoints["dspace_unibague"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unibague"]["checkpoint"] = {}
endpoints["dspace_unibague"]["checkpoint"]["enabled"] = True
endpoints["dspace_unibague"]["checkpoint"]["selective"] = False
endpoints["dspace_unibague"]["checkpoint"]["days"] = 30
endpoints["dspace_utb"] = {}
endpoints["dspace_utb"]["enabled"] = True
endpoints["dspace_utb"]["name"] = "UNIVERSIDAD TECNOLOGICA DE BOLIVAR"
endpoints["dspace_utb"]["ror"] = "https://ror.org/01d171k92"
endpoints["dspace_utb"]["url"] = "https://repositorio.utb.edu.co/oai/request"
endpoints["dspace_utb"]["metadataPrefix"] = "dim"
endpoints["dspace_utb"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_utb"]["checkpoint"] = {}
endpoints["dspace_utb"]["checkpoint"]["enabled"] = True
endpoints["dspace_utb"]["checkpoint"]["selective"] = False
endpoints["dspace_utb"]["checkpoint"]["days"] = 30
endpoints["dspace_udca"] = {}
endpoints["dspace_udca"]["enabled"] = True
endpoints["dspace_udca"]["name"] = "UNIVERSIDAD DE CIENCIAS APLICADAS Y AMBIENTALES - UDCA"
endpoints["dspace_udca"]["ror"] = "https://ror.org/01h2taq97"
endpoints["dspace_udca"]["url"] = "https://repository.udca.edu.co/server/oai/request"
endpoints["dspace_udca"]["metadataPrefix"] = "dim"
endpoints["dspace_udca"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_udca"]["checkpoint"] = {}
endpoints["dspace_udca"]["checkpoint"]["enabled"] = True
endpoints["dspace_udca"]["checkpoint"]["selective"] = False
endpoints["dspace_udca"]["checkpoint"]["days"] = 30
endpoints["dspace_unad"] = {}
endpoints["dspace_unad"]["enabled"] = True
endpoints["dspace_unad"]["name"] = "UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA UNAD"
endpoints["dspace_unad"]["ror"] = "https://ror.org/047179s14"
endpoints["dspace_unad"]["url"] = "https://repository.unad.edu.co/oai/request"
endpoints["dspace_unad"]["metadataPrefix"] = "dim"
endpoints["dspace_unad"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unad"]["checkpoint"] = {}
endpoints["dspace_unad"]["checkpoint"]["enabled"] = True
endpoints["dspace_unad"]["checkpoint"]["selective"] = False
endpoints["dspace_unad"]["checkpoint"]["days"] = 30
endpoints["dspace_esap"] = {}
endpoints["dspace_esap"]["enabled"] = True
endpoints["dspace_esap"]["name"] = "ESCUELA SUPERIOR DE ADMINISTRACION PUBLICA-ESAP-"
endpoints["dspace_esap"]["ror"] = "https://ror.org/03vhr8v79"
endpoints["dspace_esap"]["url"] = "https://repositoriocdim.esap.edu.co/oai/request"
endpoints["dspace_esap"]["metadataPrefix"] = "dim"
endpoints["dspace_esap"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_esap"]["checkpoint"] = {}
endpoints["dspace_esap"]["checkpoint"]["enabled"] = True
endpoints["dspace_esap"]["checkpoint"]["selective"] = False
endpoints["dspace_esap"]["checkpoint"]["days"] = 30
endpoints["dspace_endeporte"] = {}
endpoints["dspace_endeporte"]["enabled"] = True
endpoints["dspace_endeporte"]["name"] = "ESCUELA NACIONAL DEL DEPORTE"
endpoints["dspace_endeporte"]["ror"] = "https://ror.org/01wsvqj37"
endpoints["dspace_endeporte"]["url"] = "https://repositorio.endeporte.edu.co/oai/request"
endpoints["dspace_endeporte"]["metadataPrefix"] = "dim"
endpoints["dspace_endeporte"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_endeporte"]["checkpoint"] = {}
endpoints["dspace_endeporte"]["checkpoint"]["enabled"] = True
endpoints["dspace_endeporte"]["checkpoint"]["selective"] = False
endpoints["dspace_endeporte"]["checkpoint"]["days"] = 30
endpoints["dspace_bellasartes"] = {}
endpoints["dspace_bellasartes"]["enabled"] = True
endpoints["dspace_bellasartes"]["name"] = "INSTITUTO DEPARTAMENTAL DE BELLAS ARTES"
endpoints["dspace_bellasartes"]["ror"] = "https://ror.org/03kcqne70"
endpoints["dspace_bellasartes"]["url"] = "https://repository.bellasartes.edu.co/oai/request"
endpoints["dspace_bellasartes"]["metadataPrefix"] = "dim"
endpoints["dspace_bellasartes"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_bellasartes"]["checkpoint"] = {}
endpoints["dspace_bellasartes"]["checkpoint"]["enabled"] = True
endpoints["dspace_bellasartes"]["checkpoint"]["selective"] = False
endpoints["dspace_bellasartes"]["checkpoint"]["days"] = 30
endpoints["dspace_universidadean"] = {}
endpoints["dspace_universidadean"]["enabled"] = True
endpoints["dspace_universidadean"]["name"] = "INSTITUTO UNIVERSITARIO DE LA PAZ"
endpoints["dspace_universidadean"]["ror"] = "https://ror.org/0034jpk25"
endpoints["dspace_universidadean"]["url"] = (
    "https://repository.universidadean.edu.co/server/oai/request"
)
endpoints["dspace_universidadean"]["metadataPrefix"] = "dim"
endpoints["dspace_universidadean"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_universidadean"]["checkpoint"] = {}
endpoints["dspace_universidadean"]["checkpoint"]["enabled"] = True
endpoints["dspace_universidadean"]["checkpoint"]["selective"] = False
endpoints["dspace_universidadean"]["checkpoint"]["days"] = 30
endpoints["dspace_elpoli"] = {}
endpoints["dspace_elpoli"]["enabled"] = True
endpoints["dspace_elpoli"]["name"] = "POLITECNICO COLOMBIANO JAIME ISAZA CADAVID"
endpoints["dspace_elpoli"]["ror"] = "https://ror.org/056g73y51"
endpoints["dspace_elpoli"]["url"] = "https://repositorio.elpoli.edu.co/server/oai/request"
endpoints["dspace_elpoli"]["metadataPrefix"] = "dim"
endpoints["dspace_elpoli"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_elpoli"]["checkpoint"] = {}
endpoints["dspace_elpoli"]["checkpoint"]["enabled"] = True
endpoints["dspace_elpoli"]["checkpoint"]["selective"] = False
endpoints["dspace_elpoli"]["checkpoint"]["days"] = 30
endpoints["dspace_uceva"] = {}
endpoints["dspace_uceva"]["enabled"] = True
endpoints["dspace_uceva"]["name"] = "UNIDAD CENTRAL DEL VALLE DEL CAUCA"
endpoints["dspace_uceva"]["ror"] = "https://ror.org/00ffq6216"
endpoints["dspace_uceva"]["url"] = "https://repositorio.uceva.edu.co/oai/request"
endpoints["dspace_uceva"]["metadataPrefix"] = "dim"
endpoints["dspace_uceva"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uceva"]["checkpoint"] = {}
endpoints["dspace_uceva"]["checkpoint"]["enabled"] = True
endpoints["dspace_uceva"]["checkpoint"]["selective"] = False
endpoints["dspace_uceva"]["checkpoint"]["days"] = 30
endpoints["dspace_iue"] = {}
endpoints["dspace_iue"]["enabled"] = True
endpoints["dspace_iue"]["name"] = "INSTITUCION UNIVERSITARIA DE ENVIGADO"
endpoints["dspace_iue"]["ror"] = "https://ror.org/05jj6ma85"
endpoints["dspace_iue"]["url"] = "https://bibliotecadigital.iue.edu.co/oai/request"
endpoints["dspace_iue"]["metadataPrefix"] = "dim"
endpoints["dspace_iue"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_iue"]["checkpoint"] = {}
endpoints["dspace_iue"]["checkpoint"]["enabled"] = True
endpoints["dspace_iue"]["checkpoint"]["selective"] = False
endpoints["dspace_iue"]["checkpoint"]["days"] = 30
endpoints["dspace_unicoc"] = {}
endpoints["dspace_unicoc"]["enabled"] = True
endpoints["dspace_unicoc"]["name"] = "INSTITUCION UNIVERSITARIA COLEGIOS DE COLOMBIA - UNICOC"
endpoints["dspace_unicoc"]["ror"] = "https://ror.org/041wsqp45"
endpoints["dspace_unicoc"]["url"] = "https://repositorio.unicoc.edu.co/server/oai/request"
endpoints["dspace_unicoc"]["metadataPrefix"] = "dim"
endpoints["dspace_unicoc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unicoc"]["checkpoint"] = {}
endpoints["dspace_unicoc"]["checkpoint"]["enabled"] = True
endpoints["dspace_unicoc"]["checkpoint"]["selective"] = False
endpoints["dspace_unicoc"]["checkpoint"]["days"] = 30
endpoints["dspace_fucsalud"] = {}
endpoints["dspace_fucsalud"]["enabled"] = True
endpoints["dspace_fucsalud"]["name"] = "FUNDACION UNIVERSITARIA DE CIENCIAS DE LA SALUD"
endpoints["dspace_fucsalud"]["ror"] = "https://ror.org/02yr3f298"
endpoints["dspace_fucsalud"]["url"] = "https://repositorio.fucsalud.edu.co/server/oai/request"
endpoints["dspace_fucsalud"]["metadataPrefix"] = "dim"
endpoints["dspace_fucsalud"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_fucsalud"]["checkpoint"] = {}
endpoints["dspace_fucsalud"]["checkpoint"]["enabled"] = True
endpoints["dspace_fucsalud"]["checkpoint"]["selective"] = False
endpoints["dspace_fucsalud"]["checkpoint"]["days"] = 30
endpoints["dspace_cesa"] = {}
endpoints["dspace_cesa"]["enabled"] = True
endpoints["dspace_cesa"]["name"] = "COLEGIO DE ESTUDIOS SUPERIORES DE ADMINISTRACION-CESA-"
endpoints["dspace_cesa"]["ror"] = "https://ror.org/00gm52g34"
endpoints["dspace_cesa"]["url"] = "https://repository.cesa.edu.co/oai/request"
endpoints["dspace_cesa"]["metadataPrefix"] = "dim"
endpoints["dspace_cesa"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_cesa"]["checkpoint"] = {}
endpoints["dspace_cesa"]["checkpoint"]["enabled"] = True
endpoints["dspace_cesa"]["checkpoint"]["selective"] = False
endpoints["dspace_cesa"]["checkpoint"]["days"] = 30
endpoints["dspace_juanncorpas"] = {}
endpoints["dspace_juanncorpas"]["enabled"] = True
endpoints["dspace_juanncorpas"]["name"] = "FUNDACIÓN UNIVERSITARIA JUAN N. CORPAS"
endpoints["dspace_juanncorpas"]["ror"] = "https://ror.org/04yk0nx57"
endpoints["dspace_juanncorpas"]["url"] = "https://repositorio.juanncorpas.edu.co/oai/request"
endpoints["dspace_juanncorpas"]["metadataPrefix"] = "dim"
endpoints["dspace_juanncorpas"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_juanncorpas"]["checkpoint"] = {}
endpoints["dspace_juanncorpas"]["checkpoint"]["enabled"] = True
endpoints["dspace_juanncorpas"]["checkpoint"]["selective"] = False
endpoints["dspace_juanncorpas"]["checkpoint"]["days"] = 30
endpoints["dspace_ces"] = {}
endpoints["dspace_ces"]["enabled"] = True
endpoints["dspace_ces"]["name"] = "UNIVERSIDAD CES"
endpoints["dspace_ces"]["ror"] = "https://ror.org/037p13h95"
endpoints["dspace_ces"]["url"] = "https://repository.ces.edu.co/server/oai/request"
endpoints["dspace_ces"]["metadataPrefix"] = "dim"
endpoints["dspace_ces"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ces"]["checkpoint"] = {}
endpoints["dspace_ces"]["checkpoint"]["enabled"] = True
endpoints["dspace_ces"]["checkpoint"]["selective"] = False
endpoints["dspace_ces"]["checkpoint"]["days"] = 30
endpoints["dspace_ucp"] = {}
endpoints["dspace_ucp"]["enabled"] = True
endpoints["dspace_ucp"]["name"] = "UNIVERSIDAD CATOLICA DE PEREIRA"
endpoints["dspace_ucp"]["ror"] = "https://ror.org/029ccny38"
endpoints["dspace_ucp"]["url"] = "https://repositorio.ucp.edu.co/server/oai/request"
endpoints["dspace_ucp"]["metadataPrefix"] = "dim"
endpoints["dspace_ucp"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucp"]["checkpoint"] = {}
endpoints["dspace_ucp"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucp"]["checkpoint"]["selective"] = False
endpoints["dspace_ucp"]["checkpoint"]["days"] = 30
endpoints["dspace_konradlorenz"] = {}
endpoints["dspace_konradlorenz"]["enabled"] = True
endpoints["dspace_konradlorenz"]["name"] = "FUNDACION UNIVERSITARIA KONRAD LORENZ"
endpoints["dspace_konradlorenz"]["ror"] = "https://ror.org/03ca7a577"
endpoints["dspace_konradlorenz"]["url"] = (
    "https://repositorio.konradlorenz.edu.co/server/oai/request"
)
endpoints["dspace_konradlorenz"]["metadataPrefix"] = "dim"
endpoints["dspace_konradlorenz"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_konradlorenz"]["checkpoint"] = {}
endpoints["dspace_konradlorenz"]["checkpoint"]["enabled"] = True
endpoints["dspace_konradlorenz"]["checkpoint"]["selective"] = False
endpoints["dspace_konradlorenz"]["checkpoint"]["days"] = 30
endpoints["dspace_fumc"] = {}
endpoints["dspace_fumc"]["enabled"] = True
endpoints["dspace_fumc"]["name"] = "FUNDACION UNIVERSITARIA DE POPAYAN"
endpoints["dspace_fumc"]["ror"] = "https://ror.org/03p7h8068"
endpoints["dspace_fumc"]["url"] = "https://repositorio.fumc.edu.co/oai/request"
endpoints["dspace_fumc"]["metadataPrefix"] = "dim"
endpoints["dspace_fumc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_fumc"]["checkpoint"] = {}
endpoints["dspace_fumc"]["checkpoint"]["enabled"] = True
endpoints["dspace_fumc"]["checkpoint"]["selective"] = False
endpoints["dspace_fumc"]["checkpoint"]["days"] = 30
endpoints["dspace_ucatolicaluisamigo"] = {}
endpoints["dspace_ucatolicaluisamigo"]["enabled"] = True
endpoints["dspace_ucatolicaluisamigo"]["name"] = "UNIVERSIDAD CATÓLICA LUIS AMIGÓ"
endpoints["dspace_ucatolicaluisamigo"]["ror"] = "https://ror.org/055d5bf90"
endpoints["dspace_ucatolicaluisamigo"]["url"] = (
    "https://repository.ucatolicaluisamigo.edu.co/server/oai/request"
)
endpoints["dspace_ucatolicaluisamigo"]["metadataPrefix"] = "dim"
endpoints["dspace_ucatolicaluisamigo"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucatolicaluisamigo"]["checkpoint"] = {}
endpoints["dspace_ucatolicaluisamigo"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucatolicaluisamigo"]["checkpoint"]["selective"] = False
endpoints["dspace_ucatolicaluisamigo"]["checkpoint"]["days"] = 30
endpoints["dspace_uniajc"] = {}
endpoints["dspace_uniajc"]["enabled"] = True
endpoints["dspace_uniajc"]["name"] = "FUNDACION CENTRO UNIVERSITARIO DE BIENESTAR RURAL"
endpoints["dspace_uniajc"]["ror"] = "https://ror.org/052c3jb45"
endpoints["dspace_uniajc"]["url"] = "https://repositorio.uniajc.edu.co/server/oai/request"
endpoints["dspace_uniajc"]["metadataPrefix"] = "dim"
endpoints["dspace_uniajc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniajc"]["checkpoint"] = {}
endpoints["dspace_uniajc"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniajc"]["checkpoint"]["selective"] = False
endpoints["dspace_uniajc"]["checkpoint"]["days"] = 30
endpoints["dspace_poligran"] = {}
endpoints["dspace_poligran"]["enabled"] = True
endpoints["dspace_poligran"]["name"] = "POLITECNICO GRANCOLOMBIANO"
endpoints["dspace_poligran"]["ror"] = "https://ror.org/00n7m6g17"
endpoints["dspace_poligran"]["url"] = "https://alejandria.poligran.edu.co/oai/request"
endpoints["dspace_poligran"]["metadataPrefix"] = "dim"
endpoints["dspace_poligran"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_poligran"]["checkpoint"] = {}
endpoints["dspace_poligran"]["checkpoint"]["enabled"] = True
endpoints["dspace_poligran"]["checkpoint"]["selective"] = False
endpoints["dspace_poligran"]["checkpoint"]["days"] = 30
endpoints["dspace_ceipa"] = {}
endpoints["dspace_ceipa"]["enabled"] = True
endpoints["dspace_ceipa"]["name"] = "FUNDACION UNIVERSITARIA-CEIPA-"
endpoints["dspace_ceipa"]["ror"] = "https://ror.org/03e55jv37"
endpoints["dspace_ceipa"]["url"] = "https://repositorio.ceipa.edu.co/server/oai/request"
endpoints["dspace_ceipa"]["metadataPrefix"] = "dim"
endpoints["dspace_ceipa"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ceipa"]["checkpoint"] = {}
endpoints["dspace_ceipa"]["checkpoint"]["enabled"] = True
endpoints["dspace_ceipa"]["checkpoint"]["selective"] = False
endpoints["dspace_ceipa"]["checkpoint"]["days"] = 30
endpoints["dspace_areandina"] = {}
endpoints["dspace_areandina"]["enabled"] = True
endpoints["dspace_areandina"]["name"] = "FUNDACION UNIVERSITARIA DEL AREA ANDINA"
endpoints["dspace_areandina"]["ror"] = "https://ror.org/01hb6tn62"
endpoints["dspace_areandina"]["url"] = "https://digitk.areandina.edu.co/server/oai/request"
endpoints["dspace_areandina"]["metadataPrefix"] = "dim"
endpoints["dspace_areandina"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_areandina"]["checkpoint"] = {}
endpoints["dspace_areandina"]["checkpoint"]["enabled"] = True
endpoints["dspace_areandina"]["checkpoint"]["selective"] = False
endpoints["dspace_areandina"]["checkpoint"]["days"] = 30
endpoints["dspace_ecr"] = {}
endpoints["dspace_ecr"]["enabled"] = True
endpoints["dspace_ecr"]["name"] = "FUNDACION ESCUELA COLOMBIANA DE REHABILITACION"
endpoints["dspace_ecr"]["ror"] = "https://ror.org/02604an77"
endpoints["dspace_ecr"]["url"] = "https://repositorio.ecr.edu.co/server/oai/request"
endpoints["dspace_ecr"]["metadataPrefix"] = "dim"
endpoints["dspace_ecr"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ecr"]["checkpoint"] = {}
endpoints["dspace_ecr"]["checkpoint"]["enabled"] = True
endpoints["dspace_ecr"]["checkpoint"]["selective"] = False
endpoints["dspace_ecr"]["checkpoint"]["days"] = 30
endpoints["dspace_ucn"] = {}
endpoints["dspace_ucn"]["enabled"] = True
endpoints["dspace_ucn"]["name"] = "FUNDACION UNIVERSITARIA CATOLICA DEL NORTE"
endpoints["dspace_ucn"]["ror"] = "https://ror.org/051xvqh87"
endpoints["dspace_ucn"]["url"] = "https://repositorio.ucn.edu.co/server/oai/request"
endpoints["dspace_ucn"]["metadataPrefix"] = "dim"
endpoints["dspace_ucn"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucn"]["checkpoint"] = {}
endpoints["dspace_ucn"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucn"]["checkpoint"]["selective"] = False
endpoints["dspace_ucn"]["checkpoint"]["days"] = 30
endpoints["dspace_ucompensar"] = {}
endpoints["dspace_ucompensar"]["enabled"] = True
endpoints["dspace_ucompensar"]["name"] = "FUNDACIÓN UNIVERSITARIA COMPENSAR"
endpoints["dspace_ucompensar"]["ror"] = "https://ror.org/01x03t965"
endpoints["dspace_ucompensar"]["url"] = (
    "https://repositoriocrai.ucompensar.edu.co/server/oai/request"
)
endpoints["dspace_ucompensar"]["metadataPrefix"] = "dim"
endpoints["dspace_ucompensar"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ucompensar"]["checkpoint"] = {}
endpoints["dspace_ucompensar"]["checkpoint"]["enabled"] = True
endpoints["dspace_ucompensar"]["checkpoint"]["selective"] = False
endpoints["dspace_ucompensar"]["checkpoint"]["days"] = 30
endpoints["dspace_cuc"] = {}
endpoints["dspace_cuc"]["enabled"] = True
endpoints["dspace_cuc"]["name"] = "CORPORACION UNIVERSIDAD DE LA COSTA CUC"
endpoints["dspace_cuc"]["ror"] = "https://ror.org/01v5nhr20"
endpoints["dspace_cuc"]["url"] = "https://repositorio.cuc.edu.co/server/oai/request"
endpoints["dspace_cuc"]["metadataPrefix"] = "dim"
endpoints["dspace_cuc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_cuc"]["checkpoint"] = {}
endpoints["dspace_cuc"]["checkpoint"]["enabled"] = True
endpoints["dspace_cuc"]["checkpoint"]["selective"] = False
endpoints["dspace_cuc"]["checkpoint"]["days"] = 30
endpoints["dspace_escuelaing"] = {}
endpoints["dspace_escuelaing"]["enabled"] = True
endpoints["dspace_escuelaing"]["name"] = (
    "UNIVERSIDAD ESCUELA COLOMBIANA DE INGENIERIA JULIO GARAVITO"
)
endpoints["dspace_escuelaing"]["ror"] = "https://ror.org/01nxen694"
endpoints["dspace_escuelaing"]["url"] = "https://repositorio.escuelaing.edu.co/oai/request"
endpoints["dspace_escuelaing"]["metadataPrefix"] = "dim"
endpoints["dspace_escuelaing"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_escuelaing"]["checkpoint"] = {}
endpoints["dspace_escuelaing"]["checkpoint"]["enabled"] = True
endpoints["dspace_escuelaing"]["checkpoint"]["selective"] = False
endpoints["dspace_escuelaing"]["checkpoint"]["days"] = 30
endpoints["dspace_eia"] = {}
endpoints["dspace_eia"]["enabled"] = True
endpoints["dspace_eia"]["name"] = "UNIVERSIDAD EIA"
endpoints["dspace_eia"]["ror"] = "https://ror.org/04wwz3282"
endpoints["dspace_eia"]["url"] = "https://repository.eia.edu.co/server/oai/request"
endpoints["dspace_eia"]["metadataPrefix"] = "dim"
endpoints["dspace_eia"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_eia"]["checkpoint"] = {}
endpoints["dspace_eia"]["checkpoint"]["enabled"] = True
endpoints["dspace_eia"]["checkpoint"]["selective"] = False
endpoints["dspace_eia"]["checkpoint"]["days"] = 30
endpoints["dspace_unac"] = {}
endpoints["dspace_unac"]["enabled"] = True
endpoints["dspace_unac"]["name"] = "CORPORACION UNIVERSITARIA ADVENTISTA - UNAC"
endpoints["dspace_unac"]["ror"] = "https://ror.org/03jhhfg57"
endpoints["dspace_unac"]["url"] = "https://repository.unac.edu.co/oai/request"
endpoints["dspace_unac"]["metadataPrefix"] = "dim"
endpoints["dspace_unac"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unac"]["checkpoint"] = {}
endpoints["dspace_unac"]["checkpoint"]["enabled"] = True
endpoints["dspace_unac"]["checkpoint"]["selective"] = False
endpoints["dspace_unac"]["checkpoint"]["days"] = 30
endpoints["dspace_unilasallista"] = {}
endpoints["dspace_unilasallista"]["enabled"] = True
endpoints["dspace_unilasallista"]["name"] = "CORPORACION UNIVERSITARIA LASALLISTA"
endpoints["dspace_unilasallista"]["ror"] = "https://ror.org/05ynctv81"
endpoints["dspace_unilasallista"]["url"] = (
    "https://repository.unilasallista.edu.co/server/oai/request"
)
endpoints["dspace_unilasallista"]["metadataPrefix"] = "dim"
endpoints["dspace_unilasallista"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unilasallista"]["checkpoint"] = {}
endpoints["dspace_unilasallista"]["checkpoint"]["enabled"] = True
endpoints["dspace_unilasallista"]["checkpoint"]["selective"] = False
endpoints["dspace_unilasallista"]["checkpoint"]["days"] = 30
endpoints["dspace_cecar"] = {}
endpoints["dspace_cecar"]["enabled"] = True
endpoints["dspace_cecar"]["name"] = "CORPORACION UNIVERSITARIA DEL CARIBE - CECAR"
endpoints["dspace_cecar"]["ror"] = "https://ror.org/01bm9xh88"
endpoints["dspace_cecar"]["url"] = "https://repositorio.cecar.edu.co/server/oai/request"
endpoints["dspace_cecar"]["metadataPrefix"] = "dim"
endpoints["dspace_cecar"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_cecar"]["checkpoint"] = {}
endpoints["dspace_cecar"]["checkpoint"]["enabled"] = True
endpoints["dspace_cecar"]["checkpoint"]["selective"] = False
endpoints["dspace_cecar"]["checkpoint"]["days"] = 30
endpoints["dspace_unimeta"] = {}
endpoints["dspace_unimeta"]["enabled"] = True
endpoints["dspace_unimeta"]["name"] = "CORPORACION UNIVERSITARIA DEL META - UNIMETA"
endpoints["dspace_unimeta"]["ror"] = "https://ror.org/02r1xtk47"
endpoints["dspace_unimeta"]["url"] = "https://repositorio.unimeta.edu.co/oai/request"
endpoints["dspace_unimeta"]["metadataPrefix"] = "dim"
endpoints["dspace_unimeta"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unimeta"]["checkpoint"] = {}
endpoints["dspace_unimeta"]["checkpoint"]["enabled"] = True
endpoints["dspace_unimeta"]["checkpoint"]["selective"] = False
endpoints["dspace_unimeta"]["checkpoint"]["days"] = 30
endpoints["dspace_corhuila"] = {}
endpoints["dspace_corhuila"]["enabled"] = True
endpoints["dspace_corhuila"]["name"] = "CORPORACION UNIVERSITARIA DEL HUILA-CORHUILA-"
endpoints["dspace_corhuila"]["ror"] = "https://ror.org/01jc1nc57"
endpoints["dspace_corhuila"]["url"] = "https://dspace.corhuila.edu.co/server/oai/request"
endpoints["dspace_corhuila"]["metadataPrefix"] = "dim"
endpoints["dspace_corhuila"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_corhuila"]["checkpoint"] = {}
endpoints["dspace_corhuila"]["checkpoint"]["enabled"] = True
endpoints["dspace_corhuila"]["checkpoint"]["selective"] = False
endpoints["dspace_corhuila"]["checkpoint"]["days"] = 30
endpoints["dspace_udes"] = {}
endpoints["dspace_udes"]["enabled"] = True
endpoints["dspace_udes"]["name"] = "UNIVERSIDAD DE SANTANDER - UDES"
endpoints["dspace_udes"]["ror"] = "https://ror.org/03mx33742"
endpoints["dspace_udes"]["url"] = "https://repositorio.udes.edu.co/server/oai/request"
endpoints["dspace_udes"]["metadataPrefix"] = "dim"
endpoints["dspace_udes"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_udes"]["checkpoint"] = {}
endpoints["dspace_udes"]["checkpoint"]["enabled"] = True
endpoints["dspace_udes"]["checkpoint"]["selective"] = False
endpoints["dspace_udes"]["checkpoint"]["days"] = 30
endpoints["dspace_uniremington"] = {}
endpoints["dspace_uniremington"]["enabled"] = True
endpoints["dspace_uniremington"]["name"] = "CORPORACION UNIVERSITARIA REMINGTON"
endpoints["dspace_uniremington"]["ror"] = "https://ror.org/04zwxg371"
endpoints["dspace_uniremington"]["url"] = (
    "https://repositorio.uniremington.edu.co/server/oai/request"
)
endpoints["dspace_uniremington"]["metadataPrefix"] = "dim"
endpoints["dspace_uniremington"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniremington"]["checkpoint"] = {}
endpoints["dspace_uniremington"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniremington"]["checkpoint"]["selective"] = False
endpoints["dspace_uniremington"]["checkpoint"]["days"] = 30
endpoints["dspace_uniagustiniana"] = {}
endpoints["dspace_uniagustiniana"]["enabled"] = True
endpoints["dspace_uniagustiniana"]["name"] = "UNIVERSITARIA AGUSTINIANA- UNIAGUSTINIANA"
endpoints["dspace_uniagustiniana"]["ror"] = "https://ror.org/04thy0g29"
endpoints["dspace_uniagustiniana"]["url"] = "https://repositorio.uniagustiniana.edu.co/oai/request"
endpoints["dspace_uniagustiniana"]["metadataPrefix"] = "dim"
endpoints["dspace_uniagustiniana"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniagustiniana"]["checkpoint"] = {}
endpoints["dspace_uniagustiniana"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniagustiniana"]["checkpoint"]["selective"] = False
endpoints["dspace_uniagustiniana"]["checkpoint"]["days"] = 30
endpoints["dspace_unitec"] = {}
endpoints["dspace_unitec"]["enabled"] = True
endpoints["dspace_unitec"]["name"] = "CORPORACION UNIVERSITARIA  UNITEC"
endpoints["dspace_unitec"]["ror"] = "https://ror.org/05dyy5830"
endpoints["dspace_unitec"]["url"] = "https://repositorio.unitec.edu.co/oai/request"
endpoints["dspace_unitec"]["metadataPrefix"] = "dim"
endpoints["dspace_unitec"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unitec"]["checkpoint"] = {}
endpoints["dspace_unitec"]["checkpoint"]["enabled"] = True
endpoints["dspace_unitec"]["checkpoint"]["selective"] = False
endpoints["dspace_unitec"]["checkpoint"]["days"] = 30
endpoints["dspace_uajs"] = {}
endpoints["dspace_uajs"]["enabled"] = True
endpoints["dspace_uajs"]["name"] = "CORPORACION UNIVERSITARIA ANTONIO JOSE DE SUCRE - CORPOSUCRE"
endpoints["dspace_uajs"]["ror"] = "https://ror.org/030v7ct83"
endpoints["dspace_uajs"]["url"] = "https://bibliorepositorio.uajs.edu.co/server/oai/request"
endpoints["dspace_uajs"]["metadataPrefix"] = "dim"
endpoints["dspace_uajs"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uajs"]["checkpoint"] = {}
endpoints["dspace_uajs"]["checkpoint"]["enabled"] = True
endpoints["dspace_uajs"]["checkpoint"]["selective"] = False
endpoints["dspace_uajs"]["checkpoint"]["days"] = 30
endpoints["dspace_esdegrepositorio"] = {}
endpoints["dspace_esdegrepositorio"]["enabled"] = True
endpoints["dspace_esdegrepositorio"]["name"] = (
    "ESCUELA SUPERIOR DE GUERRA GENERAL RAFAEL REYES PRIETO"
)
endpoints["dspace_esdegrepositorio"]["ror"] = "https://ror.org/02fcfe885"
endpoints["dspace_esdegrepositorio"]["url"] = "https://www.esdegrepositorio.edu.co/oai/request"
endpoints["dspace_esdegrepositorio"]["metadataPrefix"] = "dim"
endpoints["dspace_esdegrepositorio"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_esdegrepositorio"]["checkpoint"] = {}
endpoints["dspace_esdegrepositorio"]["checkpoint"]["enabled"] = True
endpoints["dspace_esdegrepositorio"]["checkpoint"]["selective"] = False
endpoints["dspace_esdegrepositorio"]["checkpoint"]["days"] = 30
endpoints["dspace_unimayor"] = {}
endpoints["dspace_unimayor"]["enabled"] = True
endpoints["dspace_unimayor"]["name"] = "INSTITUCIÓN UNIVERSITARIA MAYOR DE CARTAGENA"
endpoints["dspace_unimayor"]["ror"] = "https://ror.org/0289gr697"
endpoints["dspace_unimayor"]["url"] = "https://repositorio.unimayor.edu.co/server/oai/request"
endpoints["dspace_unimayor"]["metadataPrefix"] = "dim"
endpoints["dspace_unimayor"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unimayor"]["checkpoint"] = {}
endpoints["dspace_unimayor"]["checkpoint"]["enabled"] = True
endpoints["dspace_unimayor"]["checkpoint"]["selective"] = False
endpoints["dspace_unimayor"]["checkpoint"]["days"] = 30
endpoints["dspace_pascualbravo"] = {}
endpoints["dspace_pascualbravo"]["enabled"] = True
endpoints["dspace_pascualbravo"]["name"] = "INSTITUCIÓN UNIVERSITARIA PASCUAL BRAVO"
endpoints["dspace_pascualbravo"]["ror"] = "https://ror.org/00s1b0733"
endpoints["dspace_pascualbravo"]["url"] = (
    "https://repositorio.pascualbravo.edu.co/server/oai/request"
)
endpoints["dspace_pascualbravo"]["metadataPrefix"] = "dim"
endpoints["dspace_pascualbravo"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_pascualbravo"]["checkpoint"] = {}
endpoints["dspace_pascualbravo"]["checkpoint"]["enabled"] = True
endpoints["dspace_pascualbravo"]["checkpoint"]["selective"] = False
endpoints["dspace_pascualbravo"]["checkpoint"]["days"] = 30
endpoints["dspace_tdea"] = {}
endpoints["dspace_tdea"]["enabled"] = True
endpoints["dspace_tdea"]["name"] = "TECNOLOGICO DE ANTIOQUIA"
endpoints["dspace_tdea"]["ror"] = "https://ror.org/00s9vmn82"
endpoints["dspace_tdea"]["url"] = "https://dspace.tdea.edu.co/oai/request"
endpoints["dspace_tdea"]["metadataPrefix"] = "dim"
endpoints["dspace_tdea"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_tdea"]["checkpoint"] = {}
endpoints["dspace_tdea"]["checkpoint"]["enabled"] = True
endpoints["dspace_tdea"]["checkpoint"]["selective"] = False
endpoints["dspace_tdea"]["checkpoint"]["days"] = 30
endpoints["dspace_itm"] = {}
endpoints["dspace_itm"]["enabled"] = True
endpoints["dspace_itm"]["name"] = "INSTITUTO TECNOLOGICO METROPOLITANO"
endpoints["dspace_itm"]["ror"] = "https://ror.org/03zb5p722"
endpoints["dspace_itm"]["url"] = "https://repositorio.itm.edu.co/oai/request"
endpoints["dspace_itm"]["metadataPrefix"] = "dim"
endpoints["dspace_itm"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_itm"]["checkpoint"] = {}
endpoints["dspace_itm"]["checkpoint"]["enabled"] = True
endpoints["dspace_itm"]["checkpoint"]["selective"] = False
endpoints["dspace_itm"]["checkpoint"]["days"] = 30
endpoints["dspace_esumer"] = {}
endpoints["dspace_esumer"]["enabled"] = True
endpoints["dspace_esumer"]["name"] = "FUNDACION UNIVERSITARIA ESUMER"
endpoints["dspace_esumer"]["ror"] = "https://ror.org/00d5d1v82"
endpoints["dspace_esumer"]["url"] = "https://repositorio.esumer.edu.co/oai/request"
endpoints["dspace_esumer"]["metadataPrefix"] = "dim"
endpoints["dspace_esumer"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_esumer"]["checkpoint"] = {}
endpoints["dspace_esumer"]["checkpoint"]["enabled"] = True
endpoints["dspace_esumer"]["checkpoint"]["selective"] = False
endpoints["dspace_esumer"]["checkpoint"]["days"] = 30
endpoints["dspace_aunar"] = {}
endpoints["dspace_aunar"]["enabled"] = False  # no funcionan los links a los identificadores
endpoints["dspace_aunar"]["name"] = "CORPORACION UNIVERSITARIA AUTONOMA DE NARIÑO -AUNAR-"
endpoints["dspace_aunar"]["ror"] = "https://ror.org/015rec412"
endpoints["dspace_aunar"]["url"] = "http://repositorio.aunar.edu.co:8080/oai/request"
endpoints["dspace_aunar"]["metadataPrefix"] = "dim"
endpoints["dspace_aunar"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_aunar"]["checkpoint"] = {}
endpoints["dspace_aunar"]["checkpoint"]["enabled"] = True
endpoints["dspace_aunar"]["checkpoint"]["selective"] = False
endpoints["dspace_aunar"]["checkpoint"]["days"] = 30
endpoints["dspace_unicomfacauca"] = {}
endpoints["dspace_unicomfacauca"]["enabled"] = True
endpoints["dspace_unicomfacauca"]["name"] = "CORPORACION UNIVERSITARIA COMFACAUCA - UNICOMFACAUCA"
endpoints["dspace_unicomfacauca"]["ror"] = "https://ror.org/007k0m436"
endpoints["dspace_unicomfacauca"]["url"] = "https://repositorio.unicomfacauca.edu.co/oai/request"
endpoints["dspace_unicomfacauca"]["metadataPrefix"] = "dim"
endpoints["dspace_unicomfacauca"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unicomfacauca"]["checkpoint"] = {}
endpoints["dspace_unicomfacauca"]["checkpoint"]["enabled"] = True
endpoints["dspace_unicomfacauca"]["checkpoint"]["selective"] = False
endpoints["dspace_unicomfacauca"]["checkpoint"]["days"] = 30
endpoints["dspace_itc"] = {}
endpoints["dspace_itc"]["enabled"] = True
endpoints["dspace_itc"]["name"] = "ESCUELA TECNOLOGICA INSTITUTO TECNICO CENTRAL"
endpoints["dspace_itc"]["ror"] = "https://ror.org/04kbsj707"
endpoints["dspace_itc"]["url"] = "https://repositorio.itc.edu.co/oai/request"
endpoints["dspace_itc"]["metadataPrefix"] = "dim"
endpoints["dspace_itc"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_itc"]["checkpoint"] = {}
endpoints["dspace_itc"]["checkpoint"]["enabled"] = True
endpoints["dspace_itc"]["checkpoint"]["selective"] = False
endpoints["dspace_itc"]["checkpoint"]["days"] = 30
endpoints["dspace_itfip"] = {}
endpoints["dspace_itfip"]["enabled"] = True
endpoints["dspace_itfip"]["name"] = "INSTITUTO TOLIMENSE DE FORMACION TECNICA PROFESIONAL"
endpoints["dspace_itfip"]["ror"] = "https://ror.org/03e79yx85"
endpoints["dspace_itfip"]["url"] = "https://repositorio.itfip.edu.co/oai/request"
endpoints["dspace_itfip"]["metadataPrefix"] = "dim"
endpoints["dspace_itfip"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_itfip"]["checkpoint"] = {}
endpoints["dspace_itfip"]["checkpoint"]["enabled"] = True
endpoints["dspace_itfip"]["checkpoint"]["selective"] = False
endpoints["dspace_itfip"]["checkpoint"]["days"] = 30
endpoints["dspace_metabiblioteca"] = {}
endpoints["dspace_metabiblioteca"]["enabled"] = True
endpoints["dspace_metabiblioteca"]["name"] = "INSTITUCION UNIVERSITARIA EAM"
endpoints["dspace_metabiblioteca"]["ror"] = "https://ror.org/00d5d1v82"
endpoints["dspace_metabiblioteca"]["url"] = (
    "https://uniquindio-dspace.metabiblioteca.com/server/oai/request"
)
endpoints["dspace_metabiblioteca"]["metadataPrefix"] = "dim"
endpoints["dspace_metabiblioteca"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_metabiblioteca"]["checkpoint"] = {}
endpoints["dspace_metabiblioteca"]["checkpoint"]["enabled"] = True
endpoints["dspace_metabiblioteca"]["checkpoint"]["selective"] = False
endpoints["dspace_metabiblioteca"]["checkpoint"]["days"] = 30
endpoints["dspace_educacionbogota"] = {}
endpoints["dspace_educacionbogota"]["enabled"] = True
endpoints["dspace_educacionbogota"]["name"] = "CORPORACION ACADEMIA SUPERIOR DE ARTES"
endpoints["dspace_educacionbogota"]["ror"] = "https://ror.org/00zy6vr46"
endpoints["dspace_educacionbogota"]["url"] = (
    "https://repositoriosed.educacionbogota.edu.co/server/oai/request"
)
endpoints["dspace_educacionbogota"]["metadataPrefix"] = "dim"
endpoints["dspace_educacionbogota"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_educacionbogota"]["checkpoint"] = {}
endpoints["dspace_educacionbogota"]["checkpoint"]["enabled"] = True
endpoints["dspace_educacionbogota"]["checkpoint"]["selective"] = False
endpoints["dspace_educacionbogota"]["checkpoint"]["days"] = 30
endpoints["dspace_cun"] = {}
endpoints["dspace_cun"]["enabled"] = True
endpoints["dspace_cun"]["name"] = "CORPORACIÓN UNIFICADA HISPANOAMERICANA DE EDUCACIÓN SUPERIOR"
endpoints["dspace_cun"]["ror"] = "https://ror.org/04axvmf19"
endpoints["dspace_cun"]["url"] = "https://repositorio.cun.edu.co/oai/request"
endpoints["dspace_cun"]["metadataPrefix"] = "dim"
endpoints["dspace_cun"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_cun"]["checkpoint"] = {}
endpoints["dspace_cun"]["checkpoint"]["enabled"] = True
endpoints["dspace_cun"]["checkpoint"]["selective"] = False
endpoints["dspace_cun"]["checkpoint"]["days"] = 30
endpoints["dspace_artesaniasdecolombia"] = {}
endpoints["dspace_artesaniasdecolombia"]["enabled"] = True
endpoints["dspace_artesaniasdecolombia"]["name"] = "CORPORACION ESCUELA TECNOLOGICA DEL ORIENTE"
endpoints["dspace_artesaniasdecolombia"]["ror"] = "https://ror.org/03qngxd77"
endpoints["dspace_artesaniasdecolombia"]["url"] = (
    "https://repositorio.artesaniasdecolombia.com.co/oai/request"
)
endpoints["dspace_artesaniasdecolombia"]["metadataPrefix"] = "dim"
endpoints["dspace_artesaniasdecolombia"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_artesaniasdecolombia"]["checkpoint"] = {}
endpoints["dspace_artesaniasdecolombia"]["checkpoint"]["enabled"] = True
endpoints["dspace_artesaniasdecolombia"]["checkpoint"]["selective"] = False
endpoints["dspace_artesaniasdecolombia"]["checkpoint"]["days"] = 30
endpoints["dspace_ecci"] = {}
endpoints["dspace_ecci"]["enabled"] = True
endpoints["dspace_ecci"]["name"] = "UNIVERSIDAD ECCI"
endpoints["dspace_ecci"]["ror"] = "https://ror.org/01vf7gd47"
endpoints["dspace_ecci"]["url"] = "https://repositorio.ecci.edu.co/oai/request"
endpoints["dspace_ecci"]["metadataPrefix"] = "dim"
endpoints["dspace_ecci"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_ecci"]["checkpoint"] = {}
endpoints["dspace_ecci"]["checkpoint"]["enabled"] = True
endpoints["dspace_ecci"]["checkpoint"]["selective"] = False
endpoints["dspace_ecci"]["checkpoint"]["days"] = 30
endpoints["dspace_icanh"] = {}
endpoints["dspace_icanh"]["enabled"] = True
endpoints["dspace_icanh"]["name"] = "INSTITUTO CARO Y CUERVO"
endpoints["dspace_icanh"]["ror"] = "https://ror.org/01a27ax82"
endpoints["dspace_icanh"]["url"] = "https://repositorio.icanh.gov.co/server/oai/request"
endpoints["dspace_icanh"]["metadataPrefix"] = "dim"
endpoints["dspace_icanh"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_icanh"]["checkpoint"] = {}
endpoints["dspace_icanh"]["checkpoint"]["enabled"] = True
endpoints["dspace_icanh"]["checkpoint"]["selective"] = False
endpoints["dspace_icanh"]["checkpoint"]["days"] = 30
endpoints["dspace_sena"] = {}
endpoints["dspace_sena"]["enabled"] = True
endpoints["dspace_sena"]["name"] = "SERVICIO NACIONAL DE APRENDIZAJE-SENA-"
endpoints["dspace_sena"]["ror"] = "https://ror.org/01yz56j89"
endpoints["dspace_sena"]["url"] = "https://repositorio.sena.edu.co/oai/request"
endpoints["dspace_sena"]["metadataPrefix"] = "dim"
endpoints["dspace_sena"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_sena"]["checkpoint"] = {}
endpoints["dspace_sena"]["checkpoint"]["enabled"] = True
endpoints["dspace_sena"]["checkpoint"]["selective"] = False
endpoints["dspace_sena"]["checkpoint"]["days"] = 30
endpoints["dspace_uniclaretiana"] = {}
endpoints["dspace_uniclaretiana"]["enabled"] = (
    False  # no tiene ror, busqué manualmente en ror.org y no está
)
endpoints["dspace_uniclaretiana"]["name"] = "FUNDACION UNIVERSITARIA CLARETIANA - UNICLARETIANA"
endpoints["dspace_uniclaretiana"]["ror"] = "https://ror.org/0541h6s03"
endpoints["dspace_uniclaretiana"]["url"] = (
    "https://repositorio.uniclaretiana.edu.co/server/oai/request"
)
endpoints["dspace_uniclaretiana"]["metadataPrefix"] = "dim"
endpoints["dspace_uniclaretiana"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniclaretiana"]["checkpoint"] = {}
endpoints["dspace_uniclaretiana"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniclaretiana"]["checkpoint"]["selective"] = False
endpoints["dspace_uniclaretiana"]["checkpoint"]["days"] = 30
endpoints["dspace_unimagdalena"] = {}
endpoints["dspace_unimagdalena"]["enabled"] = True
endpoints["dspace_unimagdalena"]["name"] = "UNIVERSIDAD DEL MAGDALENA - UNIMAGDALENA"
endpoints["dspace_unimagdalena"]["ror"] = "https://ror.org/038mvjn28"
endpoints["dspace_unimagdalena"]["url"] = (
    "https://repositoriooraloteca.unimagdalena.edu.co/server/oai/request"
)
endpoints["dspace_unimagdalena"]["metadataPrefix"] = "dim"
endpoints["dspace_unimagdalena"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_unimagdalena"]["checkpoint"] = {}
endpoints["dspace_unimagdalena"]["checkpoint"]["enabled"] = True
endpoints["dspace_unimagdalena"]["checkpoint"]["selective"] = False
endpoints["dspace_unimagdalena"]["checkpoint"]["days"] = 30
endpoints["dspace_uniautonoma"] = {}
endpoints["dspace_uniautonoma"]["enabled"] = True
endpoints["dspace_uniautonoma"]["name"] = "UNIVERSIDAD AUTONOMA DEL CARIBE- UNIAUTONOMA"
endpoints["dspace_uniautonoma"]["ror"] = "https://ror.org/05gqfsf87"
endpoints["dspace_uniautonoma"]["url"] = "https://repositorio.uniautonoma.edu.co/server/oai/request"
endpoints["dspace_uniautonoma"]["metadataPrefix"] = "dim"
endpoints["dspace_uniautonoma"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniautonoma"]["checkpoint"] = {}
endpoints["dspace_uniautonoma"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniautonoma"]["checkpoint"]["selective"] = False
endpoints["dspace_uniautonoma"]["checkpoint"]["days"] = 30
endpoints["dspace_libertadores"] = {}
endpoints["dspace_libertadores"]["enabled"] = True
endpoints["dspace_libertadores"]["name"] = "FUNDACION UNIVERSITARIA LOS LIBERTADORES"
endpoints["dspace_libertadores"]["ror"] = "https://ror.org/05pm0vd24"
endpoints["dspace_libertadores"]["url"] = (
    "https://repository.libertadores.edu.co/server/oai/request"
)
endpoints["dspace_libertadores"]["metadataPrefix"] = "dim"
endpoints["dspace_libertadores"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_libertadores"]["checkpoint"] = {}
endpoints["dspace_libertadores"]["checkpoint"]["enabled"] = True
endpoints["dspace_libertadores"]["checkpoint"]["selective"] = False
endpoints["dspace_libertadores"]["checkpoint"]["days"] = 30
endpoints["dspace_uniagraria"] = {}
endpoints["dspace_uniagraria"]["enabled"] = True
endpoints["dspace_uniagraria"]["name"] = "FUNDACION UNIVERSITARIA AGRARIA DE COLOMBIA -UNIAGRARIA-"
endpoints["dspace_uniagraria"]["ror"] = "https://ror.org/00kt2hh26"
endpoints["dspace_uniagraria"]["url"] = "https://repository.uniagraria.edu.co/server/oai/request"
endpoints["dspace_uniagraria"]["metadataPrefix"] = "dim"
endpoints["dspace_uniagraria"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniagraria"]["checkpoint"] = {}
endpoints["dspace_uniagraria"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniagraria"]["checkpoint"]["selective"] = False
endpoints["dspace_uniagraria"]["checkpoint"]["days"] = 30
endpoints["dspace_uniagraria"] = {}
endpoints["dspace_uniagraria"]["enabled"] = True
endpoints["dspace_uniagraria"]["name"] = "FUNDACION UNIVERSITARIA AGRARIA DE COLOMBIA -UNIAGRARIA-"
endpoints["dspace_uniagraria"]["ror"] = "https://ror.org/00kt2hh26"
endpoints["dspace_uniagraria"]["url"] = "https://repository.uniagraria.edu.co/server/oai/request"
endpoints["dspace_uniagraria"]["metadataPrefix"] = "dim"
endpoints["dspace_uniagraria"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_uniagraria"]["checkpoint"] = {}
endpoints["dspace_uniagraria"]["checkpoint"]["enabled"] = True
endpoints["dspace_uniagraria"]["checkpoint"]["selective"] = False
endpoints["dspace_uniagraria"]["checkpoint"]["days"] = 30
endpoints["dspace_banrep"] = {}
endpoints["dspace_banrep"]["enabled"] = False
endpoints["dspace_banrep"]["name"] = "Banco de la República Colombia"
endpoints["dspace_banrep"]["ror"] = "https://ror.org/01shra089"
endpoints["dspace_banrep"]["url"] = "https://repositorio.banrep.gov.co/server/oai/request"
endpoints["dspace_banrep"]["metadataPrefix"] = "dim"
endpoints["dspace_banrep"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_banrep"]["checkpoint"] = {}
endpoints["dspace_banrep"]["checkpoint"]["enabled"] = True
endpoints["dspace_banrep"]["checkpoint"]["selective"] = False
endpoints["dspace_banrep"]["checkpoint"]["days"] = 30
endpoints["dspace_redinvcol"] = {}
endpoints["dspace_redinvcol"]["enabled"] = False
endpoints["dspace_redinvcol"]["name"] = "Red Investigadores Economia Colombia"
endpoints["dspace_redinvcol"]["ror"] = ""
endpoints["dspace_redinvcol"]["url"] = (
    "https://repositorio.redinvestigadores.org/server/oai/request"
)
endpoints["dspace_redinvcol"]["metadataPrefix"] = "dim"
endpoints["dspace_redinvcol"]["rate_limit"] = {"calls": 10000, "secs": 1}
endpoints["dspace_redinvcol"]["checkpoint"] = {}
endpoints["dspace_redinvcol"]["checkpoint"]["enabled"] = True
endpoints["dspace_redinvcol"]["checkpoint"]["selective"] = False
endpoints["dspace_redinvcol"]["checkpoint"]["days"] = 30
